# .github/workflows/build-macos.yml
name: Build macOS DMG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app numpy

    - name: Install create-dmg
      run: |
        brew install create-dmg

    - name: Build .app with py2app
      run: |
        python setup.py py2app

    - name: Create DMG
      run: |
        mkdir -p release
        create-dmg \
          --overwrite \
          --volname "PriceBot" \
          dist/PriceBot.app \
          release/PriceBot.dmg

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: PriceBot-macos-dmg
        path: release/PriceBot.dmg
